### ISSUE TITLE
multiQC figure 

### ISSUE THREAD

**Issue by shannonekj** [dib-lab/2020-workflows-paper#31]
From @taylorreiter's comment on PR #30 the multiQC figure needs a bit more explanation & to not be so pixelated. I suggest the following update:
[multiqc_viz.pdf](https://github.com/dib-lab/2020-workflows-paper/files/4753996/multiqc_viz.pdf)

**Comment by taylorreiter** [comment]
@shannonekj , did you put this in as a PR? I love this update!

**Comment by taylorreiter** [comment]
Just had a thought though...should the multiqc be replaced a multiqc run of just those 4 files? it's a little confusing where all the extra lines come from given the current input

**Comment by taylorreiter** [comment]
thoughts @bluegenes ?

**Comment by bluegenes** [comment]
yes! I was thinking that too

**Comment by shannonekj** [comment]
I didn't put it in a PR but would be happy to update the figure with a new multiqc image and put it in a PR

**Comment by taylorreiter** [comment]
closed via #37 and #38
