### ISSUE TITLE
CWL is not interchangeable with WDL

### ISSUE THREAD

**Issue by mr-c** [dib-lab/2020-workflows-paper#35]
https://github.com/dib-lab/2020-workflows-paper/blob/82f0f8c56153f7a5c1badb29c63f9b3c39d4f540/content/04.workflows-and-software.md

> Common Workflow Language (CWL) and Workflow Description Language (WDL) are interchangeable formats 

This is not true (alas!)

**Comment by ctb** [comment]
yes, I think the right word is "interchange" not "interchangeable" :).

**Comment by ctb** [comment]
(another key point is that WDL and CWL are not primarily focused on being read and written by humans as opposed to programs)

**Comment by mr-c** [comment]
CWL is interested in being read and written by humans, that's why it is YAML based and not protobufs or XML 😁 (How well we suceeded is another matter)
